name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has not seen activity in a while, we are closing it in the meantime. Reply to this issue to re-open.'
        stale-pr-message: 'This pull request has not seen activity in a while, we are closing it in the meantime. Reply to this issue to re-open.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
